# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Prompt for prompt generation
  - trigger: ":prp"
    vars:
      - name: model
        type: choice
        params:
          values:
            - "Gemini Pro"
            - "ChatGPT o3"
    replace: |
      Tu es un expert en prompt engineering et en intelligence artificielle. Je souhaite que tu sois mon créateur de prompt attitré. Ton nom est « Promptor » et c’est comme ça que je vais t’appeler désormais.

      Ton objectif est de me rédiger le meilleur prompt possible selon mes objectifs. Ton prompt doit être rédigé et optimisé pour une requête à {{model}}.

      Pour cela, tu vas construire ta réponse de la manière suivante :

      Partie 1 : Le Prompt

      {Fournis-moi le meilleur prompt possible selon ma demande}

      Partie 2 : La critique

      {Réalise une critique sévère du prompt. Pour ça, commence par donner visuellement une note de 0 à 5 étoiles sur 5 pour le prompt (de 0 pour médiocre à 5 pour optimal) et rédige ensuite un paragraphe concis présentant les améliorations à apporter pour que le prompt soit un prompt 5 étoiles. Toutes les hypothèses et/ou problèmes doivent être traités dans ta critique}

      Partie 3 : Les questions

      {Dresse la liste des questions dont la réponse t’est indispensable pour améliorer ton prompt. Pour tout besoin d’information supplémentaire, de contexte ou de précision sur certains points, pose-moi une question. Rédige tes questions sous forme de liste à puce et limite-toi aux questions réellement indispensables}

      Après avoir reçu ta réponse en 3 parties, je vais répondre à tes questions et tu vas répéter ensuite le process en 3 parties. Nous allons continuer à itérer jusqu’à obtenir le prompt parfait.

      Pour ton prompt, tu dois absolument attribuer un ou plusieurs rôles à ChatGPT en fonction de la tâche à réaliser.

      ---

      Voici notre première description de prompt :

  # Prompt for video transcription summary
  - trigger: ":prt"
    replace: |
      # Prompt : Résumé HTML Structuré

      Transforme le contenu fourni (article, vidéo YouTube, podcast, etc.) en un résumé HTML complet, structuré et visuellement clair.

      ## Format de sortie

      Génère un fichier HTML autonome avec le style suivant :

      ### Design
      - **Palette** : Sky blue (`#0ea5e9`) comme couleur primaire, gris slate (`#64748b`) comme accent secondaire, fond crème léger (`#fafafa`)
      - **Typographie** : Segoe UI / system-ui, line-height 1.8 pour une lecture confortable
      - **Layout** : Centré, max-width 800px, padding généreux

      ### Structure du document

      1. **Header centré** : Titre avec emoji contextuel + source/auteur + trait bleu de séparation

      2. **Highlight box** (optionnel) : Si une statistique ou un chiffre clé résume le contenu, l'afficher en grand dans une box bleu clair

      3. **Sections** : Une par concept/chapitre majeur, avec :
         - Icône dans un carré arrondi bleu clair
         - Titre + sous-titre en gris
         - Séparateur border-bottom entre sections

      4. **Cards** pour les informations clés :
         - `.card-science` (bordure gauche bleue) : études, données, recherches
         - `.card-example` (bordure gauche grise, fond gris très clair) : exemples, citations, cas concrets

      5. **Timeline/Steps** : Pour les étapes ou processus
         - Ligne verticale grise à gauche
         - Points bleus centrés sur la ligne (position: `left: calc(-1.5rem - 8px)`)

      6. **Action box** : Fond bleu clair + bordure gauche bleue pour les points clés à retenir ou actions à faire

      7. **Summary pills** : En bas, des pills arrondis récapitulant les points essentiels avec emoji + label

      ### Règles de contenu

      - **Exhaustif** : Ne rien oublier d'important, capturer tous les concepts clés
      - **Hiérarchisé** : Du plus important au plus détaillé
      - **Concis** : Phrases courtes, pas de fluff
      - **Tags** : Utiliser des `<span class="tag">` pour les chiffres/statistiques importants
      - **Pas de orange/jaune** : Ça ressemble à des warnings, rester sur bleu + gris

      ### CSS à utiliser

      ```css
      * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
      }

      body {
          --primary: #0ea5e9;
          --primary-light: #e0f2fe;
          --primary-dark: #0284c7;
          --accent: #64748b;
          --accent-light: #f1f5f9;
          --text: #1e293b;
          --muted: #64748b;
          --bg: #fafafa;
          --card: #ffffff;
          --border: #e2e8f0;
          
          font-family: 'Segoe UI', system-ui, sans-serif;
          background: var(--bg);
          color: var(--text);
          line-height: 1.8;
          padding: 2.5rem 2rem;
      }

      .container {
          max-width: 800px;
          margin: 0 auto;
      }

      header {
          text-align: center;
          margin-bottom: 2.5rem;
      }

      h1 {
          font-size: 2rem;
          font-weight: 600;
          margin-bottom: 0.5rem;
      }

      .meta {
          color: var(--muted);
          font-size: 0.95rem;
      }

      .divider {
          width: 60px;
          height: 3px;
          background: var(--primary);
          margin: 1.5rem auto;
          border-radius: 2px;
      }

      .highlight-box {
          background: linear-gradient(135deg, var(--primary-light) 0%, #f0f9ff 100%);
          padding: 1.25rem;
          border-radius: 10px;
          margin-bottom: 2rem;
          text-align: center;
      }

      .highlight-box .big-number {
          font-size: 2.5rem;
          font-weight: 700;
          color: var(--primary);
      }

      .highlight-box .label {
          color: var(--muted);
      }

      .section {
          margin-bottom: 2rem;
          padding-bottom: 2rem;
          border-bottom: 1px solid var(--border);
      }

      .section:last-of-type {
          border-bottom: none;
      }

      .section-header {
          display: flex;
          align-items: center;
          gap: 1rem;
          margin-bottom: 1rem;
      }

      .section-icon {
          font-size: 1.8rem;
          width: 50px;
          height: 50px;
          background: var(--primary-light);
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
      }

      .section h2 {
          font-size: 1.25rem;
          font-weight: 600;
      }

      .section h2 .subtitle {
          display: block;
          font-size: 0.85rem;
          font-weight: 400;
          color: var(--muted);
          margin-top: 0.2rem;
      }

      .card {
          background: var(--card);
          border: 1px solid var(--border);
          border-radius: 10px;
          padding: 1rem;
          margin: 1rem 0;
      }

      .card-science {
          border-left: 3px solid var(--primary);
      }

      .card-example {
          border-left: 3px solid var(--accent);
          background: var(--accent-light);
      }

      .card h4 {
          font-size: 0.85rem;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 0.5rem;
      }

      .card-science h4 {
          color: var(--primary);
      }

      .card-example h4 {
          color: var(--accent);
      }

      .tag {
          display: inline-block;
          background: var(--primary-light);
          color: var(--primary-dark);
          padding: 0.2rem 0.5rem;
          border-radius: 4px;
          font-size: 0.85rem;
          font-weight: 600;
      }

      .steps {
          margin: 1rem 0;
          padding-left: 1.5rem;
          border-left: 2px solid var(--border);
      }

      .step {
          margin-bottom: 0.75rem;
          position: relative;
      }

      .step::before {
          content: "";
          position: absolute;
          left: calc(-1.5rem - 8px);
          top: 0.5rem;
          width: 10px;
          height: 10px;
          background: var(--primary);
          border-radius: 50%;
          border: 2px solid var(--bg);
      }

      .action-box {
          background: var(--primary-light);
          padding: 1rem;
          border-radius: 8px;
          margin-top: 1rem;
          border-left: 3px solid var(--primary);
      }

      .action-box strong {
          color: var(--primary-dark);
      }

      .summary {
          display: flex;
          flex-wrap: wrap;
          gap: 0.75rem;
          justify-content: center;
          margin-top: 2rem;
      }

      .summary-pill {
          background: var(--card);
          border: 1px solid var(--border);
          padding: 0.6rem 1rem;
          border-radius: 50px;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          font-size: 0.9rem;
      }

      .summary-pill:hover {
          border-color: var(--primary);
          background: var(--primary-light);
      }

      .summary-pill .icon {
          font-size: 1.1rem;
      }
      ```

      ## Exemple d'utilisation

      **Output** : Un fichier HTML complet et autonome suivant ce template.

      **Input** :
