".config/nvim":
  type: "git-repo"
  url: "https://github.com/LazyVim/starter"
  refreshPeriod: "24h"

{{ if .features.kemeo }}
".kemeo":
  type: "git-repo"
  url: "git@github.com:Cydonia7/dotfiles-kemeo.git"
  refreshPeriod: "24h"
{{ end }}

