".config/nvim":
  type: "git-repo"
  url: "https://github.com/LazyVim/starter"
  refreshPeriod: "24h"

{{ if .features.quotatis }}
".quotatis":
  type: "git-repo"
  url: "git@github.com:Cydonia7/dotfiles-quotatis.git"
  refreshPeriod: "24h"
{{ end }}

{{ if .features.cmi }}
".cmi":
  type: "git-repo"
  url: "git@github.com:Cydonia7/dotfiles-cmi.git"
  refreshPeriod: "24h"
{{ end }}

