".config/nvim":
  type: "git-repo"
  url: "https://github.com/LazyVim/starter"
  refreshPeriod: "24h"

{{ if .features.kemeo }}
".kemeo":
  type: "git-repo"
  url: "git@github.com:Cydonia7/dotfiles-kemeo.git"
  refreshPeriod: "24h"
{{ end }}

".config/tmux/plugins/catppuccin/tmux":
  type: "git-repo"
  url: "https://github.com/catppuccin/tmux.git"
  refreshPeriod: "24h"
  pull:
    args: ["--prune", "--force", "--tags"]

".config/tmux/plugins/tmux-plugins/tmux-cpu":
  type: "git-repo"
  url: "https://github.com/tmux-plugins/tmux-cpu"
  refreshPeriod: "24h"

".config/tmux/plugins/tmux-plugins/tmux-battery":
  type: "git-repo"
  url: "https://github.com/tmux-plugins/tmux-battery"
  refreshPeriod: "24h"

